// Email service for sending offboarding reports
import nodemailer from 'nodemailer';
import path from 'path';

export interface EmailConfig {
    service?: string;
    host?: string;
    port?: number;
    secure?: boolean;
    user: string;
    pass: string;
    from?: string;
}

export const sendOffboardingReport = async (
    userData: any,
    pdfPath: string,
    requestedEmailConfig?: {
        to?: string[];
        cc?: string[];
        subject?: string;
        body?: string;
    },
    companyConfig?: EmailConfig
) => {
    try {
        const smtpUser = companyConfig?.user || process.env.SMTP_USER;
        const smtpPass = companyConfig?.pass || process.env.SMTP_PASS;

        // Check if email credentials are properly configured
        if (!smtpUser || smtpUser === 'your-email@gmail.com' ||
            !smtpPass || smtpPass === 'your-app-password') {
            console.warn('⚠️  Email credentials not configured. Skipping email send.');
            return {
                success: true,
                messageId: 'email-skipped-no-credentials',
                message: 'Email skipped - credentials not configured'
            };
        }

        // Create transporter dynamically
        const transporter = nodemailer.createTransport({
            service: companyConfig?.service || process.env.EMAIL_SERVICE || 'gmail',
            host: companyConfig?.host || process.env.SMTP_HOST,
            port: companyConfig?.port || Number(process.env.SMTP_PORT) || 587,
            secure: companyConfig?.secure ?? (process.env.SMTP_SECURE === 'true'),
            auth: {
                user: smtpUser,
                pass: smtpPass,
            },
        });

        const to = requestedEmailConfig?.to && requestedEmailConfig.to.length > 0
            ? requestedEmailConfig.to
            : [process.env.HR_NOTIFICATION_EMAIL || 'hr@company.com'];

        const cc = requestedEmailConfig?.cc && requestedEmailConfig.cc.length > 0
            ? requestedEmailConfig.cc
            : (process.env.OFFBOARDING_CC_EMAILS ? process.env.OFFBOARDING_CC_EMAILS.split(',') : []);

        const subject = requestedEmailConfig?.subject || `Offboarding Completion Report: ${userData.username}`;

        const defaultHtml = `
            <div style="font-family: sans-serif; line-height: 1.6; color: #333;">
                <h2 style="color: #d32f2f;">Employee Offboarding Completed</h2>
                <p>Dear HR Team,</p>
                <p>This is to inform you that the offboarding process for <strong>${userData.username}</strong> has been successfully completed in the SecurePro system.</p>
                <p><strong>Employee Details:</strong></p>
                <ul>
                    <li><strong>Name:</strong> ${userData.username}</li>
                    <li><strong>Email:</strong> ${userData.email}</li>
                    <li><strong>Completion Date:</strong> ${new Date().toLocaleDateString()}</li>
                </ul>
                <p>Attached is the final checkout report containing the status of all 8 offboarding steps, asset verification, and security clearance.</p>
                <p>System access for this user has been revoked and marked as Inactive.</p>
                <br>
                <p style="font-size: 12px; color: #777;">This is an automated report generated by the SecurePro Offboarding Module.</p>
            </div>
        `;

        const html = requestedEmailConfig?.body
            ? `<div style="font-family: sans-serif; line-height: 1.6; color: #333; white-space: pre-wrap;">${requestedEmailConfig.body}</div>`
            : defaultHtml;

        const mailOptions = {
            from: companyConfig?.from || process.env.SMTP_FROM || '"SecurePro Offboarding" <noreply@securepro.com>',
            to: to.join(','),
            cc: cc.join(','),
            subject: subject,
            html: html,
            attachments: [
                {
                    filename: path.basename(pdfPath),
                    path: pdfPath
                }
            ]
        };

        const info = await transporter.sendMail(mailOptions);
        return { success: true, messageId: info.messageId };
    } catch (error: any) {
        console.error('Failed to send offboarding report email:', error);

        if (error.code === 'EAUTH') {
            return {
                success: false,
                error: 'Email authentication failed - check SMTP configuration',
                skipEmail: false
            };
        }

        return { success: false, error: error.message };
    }
};
